@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Update an author's data as librarian

actor "HTTP Client" as User
participant ":Book:book" as Rest

activate User

User -> Rest: PATCH /api/authors/{authorNumber}

alt If author is found


    alt If there is an error during update
        Rest --> User: 400/409 - error
    else Success
        Rest --> User: 200 - author updated
        Rest -> Rest: update data
    end
else If author not found
    Rest --> User: 404 - author not found
end

@enduml
