@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Register a new reader as Anonymous

actor "HTTP Client" as Anonymous
participant ":LMS" as System


activate Anonymous

Anonymous -> System: Requests to register a new reader

System --> Anonymous: 200 - ok

@enduml
