@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Get Specific Lending as Reader

actor "HTTP Client" as Anonymous
participant ":LMS" as System


activate Anonymous

Anonymous -> System: GET /api/lendings/2024/{lendingNumber}

System --> Anonymous: 200 - ok

@enduml
