@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Get a Specific Lending as Librarian

actor "HTTP Client" as Anonymous
participant ":LMS" as System


activate Anonymous

Anonymous -> System: Requests to get a specific lending

System --> Anonymous: 200 - ok

@enduml
