@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title POST register user as anonymous user

actor "HTTP Client" as User
participant ":AuthAPI" as Rest
participant "Ctrl:UserController" as Ctrl
participant "service:UserService" as Service
participant "repo:UserRepository" as Repo

activate User

User -> Rest: POST /api/public/register

Rest -> Ctrl: register(requestBody)

Ctrl -> Service: registerUser(username, password)
Service -> Repo: saveNewUser(username, password)
Repo --> Service: user created or error
Service --> Ctrl: success or error
Ctrl --> Rest: success or error

alt If there is an error
    Rest --> User: 400 - Bad Request
else Success
    Rest --> User: 201 - User created
end

@enduml



