@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title As Librarian I want to know a user’s detail given its name

actor "Librarian" as User
participant "Ctrl:ReaderController" as Ctrl
participant "service:ReaderService" as Service
participant "repo:ReaderRepository" as Repo
activate User

User -> Ctrl: GET /api/reader?name={ReaderName}
Ctrl -> Service: findByNameName(ReaderName)
Service -> Repo: findByNameName(ReaderName)
Repo --> Service: Reader or exception
Service --> Ctrl: Reader or exception
Ctrl --> User: Reader or exception

@enduml
