@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

title Register an Author as a Librarian

actor "HTTP Client" as Librarian
participant ":Book:book" as System

activate Librarian

Librarian -> System : POST /api/authors
alt If exception is returned
    System -> Librarian: 409 Conflict - Book is duplicate
end
System -> System: register data
System --> Librarian: 201 - registered author


@enduml
