@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Update data as reader

actor "HTTP Client" as Reader
participant ":System" as System
participant "Ctrl:ReaderController" as Ctrl
participant "service:ReaderService" as Service
participant "repo:ReaderRepository" as Repo
participant "reader:Reader" as ReaderObj

activate Reader

Reader -> System: PATCH /api/reader

System -> Ctrl: update(UpdateReaderRequest);
Ctrl -> Service: update(UpdateReaderRequest)
Service -> ReaderObj: applyPatch(version, UpdateReaderRequest)
Service -> Repo: save(readerObj)
Repo --> Service: success or exception
Service --> Ctrl: success or exception
Ctrl --> System: success or exception
System --> Reader: success or exception
@enduml
