@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET co-authors and their books by authorNumber as Reader

actor "HTTP Client" as Reader
participant ":BookAPI" as Rest
participant "Ctrl:AuthorsController" as Controller
participant "service:AuthorsService" as AuthorService
participant "mapper:AuthorViewMapper" as AuthorViewMapper

activate Reader

Reader -> Rest: GET /api/authors/{authorNumber}/coauthors

Rest -> Controller: getCoAuthorsByAuthor(authorNumber)

Controller -> AuthorService: findByAuthorNumber(authorNumber)
AuthorService --> Controller: Author or NotFoundException

alt Author found
    Controller -> AuthorService: findCoAuthorsByAuthorNumber(authorNumber)
    AuthorService --> Controller: List<Author>

    loop for each co-author
        Controller -> AuthorService: findBooksByAuthorNumber(coAuthor.authorNumber)
        AuthorService --> Controller: List<Book>
        Controller -> AuthorViewMapper: toCoAuthorView(coAuthor, books)
        AuthorViewMapper --> Controller: CoAuthorView
    end loop

    Controller -> AuthorViewMapper: toAuthorCoAuthorBooksView(author, coAuthorViews)
    AuthorViewMapper --> Controller: AuthorCoAuthorBooksView
    Controller --> Rest: AuthorCoAuthorBooksView

    Rest --> Reader: 200 - List<Books>

else Author not found
    Rest --> Reader: 404 - NotFoundException
end

@enduml


