@startuml
!define RECTANGLE_COLOR #ADD8E6
skinparam componentStyle rectangle
skinparam rectangle {
    BackgroundColor RECTANGLE_COLOR
    BorderColor black
    FontSize 12
    FontColor black
}
skinparam node {
    BackgroundColor white
    BorderColor black
}
skinparam arrow {
    Color black
}

rectangle "Readers" <<Container (C4)>> {
    rectangle "Readers Backend" as readers_backend
    database "H2 Database" as readers_db
}

readers_backend -[#black,plain]-(0 readers_db : JPA

@enduml








