@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET Top 5 Books as a Librarian

actor "HTTP Client" as User
participant ":LMS" as Rest



activate User

User -> Rest: ask for top 5 books
Rest --> User: List of books

@enduml