@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET Top 5 Books as a Librarian

actor "HTTP Client" as User
participant ":BookAPI" as Rest
participant "Ctrl:BookController" as Ctrl
participant "service:BookService" as Service
participant "repo:BookRepository" as Repo
participant ":BookViewMapper" as Mapper


activate User

User -> Rest: GET /api/books/top5

Rest -> Ctrl: Top5();


Ctrl -> Mapper: toBookCountView(bookService.findTop5BooksLent()))
Mapper -> Service: findTop5BooksLent()
Service -> Repo: getTop5(BookCountDTO)
Repo --> Service: list<BookCountDTO>
Service --> Mapper: list<BookCountDTO>
Mapper --> Ctrl: ListResponse<>
Ctrl --> Rest: ListResponse<>
Rest --> User: 200 OK - ListResponse<>

@enduml
